# Generated by Django 5.2.15 on 2026-06-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="Id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=100)),
                ("surname", models.CharField(db_column="Surname", max_length=100)),
                (
                    "birth_date",
                    models.DateField(blank=True, db_column="BirthDate", null=True),
                ),
                (
                    "identity_number",
                    models.CharField(
                        db_column="IdentityNumber",
                        db_index=True,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        db_column="FatherId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="father_children",
                        to="app.person",
                        to_field="identity_number",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        db_column="MotherId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mother_children",
                        to="app.person",
                        to_field="identity_number",
                    ),
                ),
            ],
            options={
                "db_table": "site_person",
            },
        ),
    ]
